name: Release Docker image

on:
  release:
    types: [created]
  push:
    branches : [release/*]

env:
  DOCKER_IMAGE: humenius/traefik-certs-dumper

jobs:
  release:
    name: Release normal (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare tags for normal build
        id: docker_meta
        uses: docker/metadata-action@v3.6.1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=true

      - name: Prepare tags for arm32v7 build
        id: docker_meta_arm32v7
        uses: docker/metadata-action@v3.6.1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=false
            suffix=-arm32v7

      - name: Prepare tags for arm64v8 build
        id: docker_meta_arm64v8
        uses: docker/metadata-action@v3.6.1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=false
            suffix=-arm64v8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3.0.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
  
      - name: Build and publish image (arm32v7)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.armhf
          platforms: linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta_arm32v7.outputs.tags }}
          labels: ${{ steps.docker_meta_arm32v7.outputs.labels }}
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}

      - name: Build and publish image (arm64v8)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.aarch64
          platforms: linux/arm64/v8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta_arm64v8.outputs.tags }}
          labels: ${{ steps.docker_meta_arm64v8.outputs.labels }}
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}

  release-alpine:
    name: Release Alpine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare tags for normal build
        id: docker_meta
        uses: docker/metadata-action@v3.6.1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=false
            suffix=-alpine
            suffix=-amd64-alpine

      - name: Prepare tags for arm32v7 build
        id: docker_meta_arm32v7
        uses: docker/metadata-action@v3.6.1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=false
            suffix=-arm32v7-alpine

      - name: Prepare tags for arm64v8 build
        id: docker_meta_arm64v8
        uses: docker/metadata-action@v3.6.1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=false
            suffix=-arm64v8-alpine

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3.0.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
  
      - name: Build and publish image (arm32v7)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile.armhf
          platforms: linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta_arm32v7.outputs.tags }}
          labels: ${{ steps.docker_meta_arm32v7.outputs.labels }}
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}

      - name: Build and publish image (arm64v8)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile.aarch64
          platforms: linux/arm64/v8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta_arm64v8.outputs.tags }}
          labels: ${{ steps.docker_meta_arm64v8.outputs.labels }}
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
